image: ubuntu:22.04

stages:
  - build
#  - package
#  - release

variables:
  DEBIAN_FRONTEND: noninteractive

before_script:
  - apt-get update
  - apt-get install -y git wget curl build-essential gcc g++ make \
      libfuse2 libglib2.0-bin desktop-file-utils libgl1-mesa-dev \
      libxkbcommon-dev qt6-base-dev qt6-declarative-dev qt6-tools-dev
  - wget https://github.com/Kitware/CMake/releases/download/v3.27.7/cmake-3.27.7-linux-x86_64.sh
  - chmod +x cmake-3.27.7-linux-x86_64.sh
  - ./cmake-3.27.7-linux-x86_64.sh --skip-license --prefix=/usr/local
  - cmake --version

#build_release:
#  stage: build
#  script:
#    - mkdir -p build && cd build
#    - cmake .. -DCMAKE_BUILD_TYPE=Release
#    - cmake --build . --parallel
#    - make -j$(nproc)
#  artifacts:
#    paths:
#      - build/

build_appimage:
  stage: build
  script:
    - echo "📦 Starting AppImage build..."
#    - mkdir -p build && cd build
#    - cmake .. -DCMAKE_BUILD_TYPE=Release
#    - make -j$(nproc)
#    - cd ..
    - chmod +x appimage_build.sh
    - ./appimage_build.sh
    - echo "📦 The End AppImage build..."
  rules:
    - if: '$CI_COMMIT_BRANCH == "v1.0.0"'
  artifacts:
    paths:
    - build/
     # - rtsm*.AppImage

#release:
#  stage: release
#  script:
#    - echo "Creating release for tag $CI_COMMIT_TAG"
#  only:
#    - tags
#  artifacts:
#    paths:
#      - rtsm*.AppImage
#  release:
#    name: "RTSM $CI_COMMIT_TAG"
#    tag_name: "$CI_COMMIT_TAG"
#    description: "Release for RTSM $CI_COMMIT_TAG"
