image: ubuntu:24.04

stages:
  - build
  
variables:
  QT_VERSION: "6.9.1"
  QT_DIR: "$CI_PROJECT_DIR/qt"
  BUILD_DIR: "$CI_PROJECT_DIR/build"
  QT_ARCHIVE_URL: "https://download.qt.io/official_releases/qt/6.9/6.9.1/qt-opensource-linux-x64-6.9.1.tar.xz"

before_script:
  - apt update && apt install -y wget build-essential cmake ninja-build libgl1-mesa-dev libxkbcommon-dev libxcb1-dev libx11-xcb-dev libxcb-glx0-dev libxcb-keysyms1-dev libxcb-image0-dev libxcb-shm0-dev libxcb-icccm4-dev libxcb-sync-dev libxcb-xfixes0-dev libxcb-shape0-dev libxcb-randr0-dev libxcb-render-util0-dev libxcb-util-dev libxcb-xinerama0-dev
  - mkdir -p $QT_DIR
  - wget $QT_ARCHIVE_URL -O qt.tar.xz
  - tar -xf qt.tar.xz -C $QT_DIR --strip-components=1
  - export CMAKE_PREFIX_PATH="$QT_DIR/lib/cmake"
  - cmake --version

build_appimage:
  stage: build
  script:
    - echo "📦 Starting AppImage build..."
    - mkdir -p $BUILD_DIR && cd $BUILD_DIR
    - cmake .. -GNinja -DCMAKE_BUILD_TYPE=Release -DCMAKE_PREFIX_PATH="$QT_DIR/lib/cmake"
    - ninja
#    - mkdir -p build && cd build
#    - cmake .. -DCMAKE_BUILD_TYPE=Release
#    - make -j$(nproc)
#    - cd ..
    - chmod +x appimage_build.sh
    - ./appimage_build.sh
    - echo "📦 The End AppImage build..."
  rules:
    - if: '$CI_COMMIT_BRANCH == "v1.0.0"'
  artifacts:
    paths:
    - build/
     # - rtsm*.AppImage

#release:
#  stage: release
#  script:
#    - echo "Creating release for tag $CI_COMMIT_TAG"
#  only:
#    - tags
#  artifacts:
#    paths:
#      - rtsm*.AppImage
#  release:
#    name: "RTSM $CI_COMMIT_TAG"
#    tag_name: "$CI_COMMIT_TAG"
#    description: "Release for RTSM $CI_COMMIT_TAG"
