image: ubuntu:22.04

stages:
  - build
#  - package
#  - release

variables:
  DEBIAN_FRONTEND: noninteractive

before_script:
    - echo "===> Installing required packages..."
    - apt-get update -qq
    - apt-get install -y wget curl unzip tar xz-utils git build-essential
    - chmod +x build_install_dependency.sh
    - ./build_install_dependency.sh
    - echo "Done build install dependency"

build_release:
  stage: build
  script:
    - mkdir -p build && cd build
    - cmake .. -DCMAKE_BUILD_TYPE=Release
    - cmake --build . --parallel
  artifacts:
    paths:
      - build/

